DROP TABLE IF EXISTS race_seats;
CREATE TABLE race_seats (state TEXT,district INTEGER,incumbent TEXT,party TEXT,category TEXT,notes TEXT, PRIMARY KEY(state,district));
INSERT INTO race_seats VALUES ('NY',1,'Nick LaLota','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NY',2,'Andrew Garbarino','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NY',3,'Tom Suozzi','D','Likely Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',4,'Laura Gillen','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',5,'Gregory Meeks','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',6,'Grace Meng','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',7,'Velazquez','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',8,'Hakeem Jeffries','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',9,'Yvette Clarke','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',10,'Dan Goldman','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',11,'Nicole Malliotakis','R','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('NY',12,'Nadler','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',13,'Adriano Espaillat','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',14,'Alexandria Ocasio-Cortez','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',15,'Ritchie Torres','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',16,'George Latimer','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',17,'Michael Lawler','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('NY',18,'Pat Ryan','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',19,'Josh Riley','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',20,'Paul Tonko','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',21,'Stefanik','R','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('NY',22,'John Mannion','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',23,'Nick Langworthy','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NY',24,'Claudia Tenney','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NY',25,'Joseph Morelle','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NY',26,'Tim Kennedy','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MA',1,'Richard Neal','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MA',2,'Jim McGovern','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MA',3,'Lori Trahan','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MA',4,'Jake Auchincloss','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MA',5,'Katherine Clark','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MA',6,'Seth Moulton','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MA',7,'Ayanna Pressley','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MA',8,'Stephen Lynch','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MA',9,'Bill Keating','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CO',1,'DeGette','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CO',2,'Joe Neguse','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CO',3,'Jeff Hurd','R','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('CO',4,'Lauren Boebert','R','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('CO',5,'Jeff Crank','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('CO',6,'Jason Crow','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CO',7,'Brittany Pettersen','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CO',8,'Gabe Evans','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('AL',1,'Moore','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AL',2,'Shomari Figures','D','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('AL',3,'Mike Rogers','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AL',4,'Robert Aderholt','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AL',5,'Dale Strong','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AL',6,'Gary Palmer','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AL',7,'Terri Sewell','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('TX',1,'Nathaniel Moran','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',2,'Crenshaw','R','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('TX',3,'Keith Self','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',4,'Pat Fallon','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',5,'Lance Gooden','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',6,'Jake Ellzey','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',7,'Lizzie Fletcher','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('TX',8,'Luttrell','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',9,'Green','D','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('TX',10,'McCaul','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',11,'August Pfluger','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',12,'Craig Goldman','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',13,'Ronny Jackson','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',14,'Randy Weber','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',15,'Monica de la Cruz','R','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('TX',16,'Veronica Escobar','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('TX',17,'Pete Sessions','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',18,'Sylvester Turner','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('TX',19,'Arrington','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',20,'Joaquin Castro','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('TX',21,'Roy','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',22,'Nehls','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',23,'Gonzales','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('TX',24,'Beth Van Duyne','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',25,'Johnson','D','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('TX',26,'Brandon Gill','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',27,'Michael Cloud','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',28,'Henry Cuellar','D','Tossup',NULL);
INSERT INTO race_seats VALUES ('TX',29,'Silvia Garcia','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('TX',30,'Crockett','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('TX',31,'John Carter','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',32,'Johnson','D','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('TX',33,'Veasey','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('TX',34,'Vicente Gonzalez','D','Tossup',NULL);
INSERT INTO race_seats VALUES ('TX',35,'Casar','D','Tossup',NULL);
INSERT INTO race_seats VALUES ('TX',36,'Brian Babin','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TX',37,'Lloyd Doggett','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('TX',38,'Hunt','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('CA',1,'LaMalfa','R','Likely Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',2,'Jared Huffman','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',3,'Kevin Kiley','R','Likely Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',4,'Mike Thompson','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',5,'Tom McClintock','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('CA',6,'Ami Bera','D','Likely Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',7,'Doris Matsui','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',8,'John Garamendi','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',9,'Josh Harder','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',10,'Mark DeSaulnier','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',11,'Pelosi','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',12,'Lateefah Simon','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',13,'Adam Gray','D','Likely Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',14,'Swalwell','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',15,'Kevin Mullin','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',16,'Sam Liccardo','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',17,'Ro Khanna','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',18,'Zoe Lofgren','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',19,'Jimmy Panetta','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',20,'Vince Fong','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('CA',21,'Jim Costa','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',22,'Valadao','R','Lean/Tilt Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',23,'Jay Obernolte','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('CA',24,'Salud Carbajal','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',25,'Raul Ruiz','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',26,'Brownley','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',27,'George Whitesides','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',28,'Judy Chu','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',29,'Luz Rivas','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',30,'Laura Friedman','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',31,'Gil Cisneros','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',32,'Brad Sherman','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',33,'Pete Aguilar','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',34,'Jimmy Gomez','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',35,'Norma Torres','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',36,'Ted Lieu','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',37,'Sydney Kamlager','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',38,'Sanchez','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',39,'Mark Takano','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',40,'Kim','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('CA',41,'Calvert','R','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',42,'Robert Garcia','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',43,'Maxine Waters','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',44,'Nanette Barragan','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',45,'Derek Tran','D','Likely Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',46,'Lou Correa','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',47,'David Min','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',48,'Issa','R','Likely Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',49,'Mike Levin','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',50,'Scott Peters','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',51,'Sara Jacobs','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CA',52,'Juan Vargas','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('FL',1,'Jimmy Patronis','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',2,'Dunn','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',3,'Kat Cammack','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',4,'Aaron Bean','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',5,'John Rutherford','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',6,'Randy Fine','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',7,'Cory Mills','R','Tilt Republican',NULL);
INSERT INTO race_seats VALUES ('FL',8,'Mike Haridopolos','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',10,'Maxwell Frost','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('FL',11,'Webster','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',12,'Gus Bilirakis','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',13,'Anna Paulina Luna','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',15,'Laurel Lee','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',16,'Buchanan','R','Tilt Republican',NULL);
INSERT INTO race_seats VALUES ('FL',17,'Greg Steube','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',18,'Scott Franklin','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',19,'Donalds','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',20,'Sheila Cherfilus-McCormick','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('FL',21,'Brian Mast','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',22,'Frankel','D','Lean/Tilt Democrat',NULL);
INSERT INTO race_seats VALUES ('FL',23,'Jared Moskowitz','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('FL',24,'Wilson','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('FL',26,'Mario Diaz-Balart','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('FL',27,'Maria Elvira Salazar','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('PA',1,'Brian Fitzpatrick','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('PA',2,'Brendan Boyle','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('PA',3,'Evans','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('PA',4,'Madeleine Dean','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('PA',5,'Mary Gay Scanlon','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('PA',6,'Chrissy Houlahan','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('PA',7,'Ryan Mackenzie','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('PA',8,'Rob Bresnahan','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('PA',9,'Dan Meuser','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('PA',10,'Scott Perry','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('PA',11,'Lloyd Smucker','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('PA',12,'Summer Lee','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('PA',13,'John Joyce','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('PA',14,'Glenn Thompson','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('PA',15,'Chris Deluzio','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('PA',16,'Mike Kelly','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OH',1,'Greg Landsman','D','Lean/Tilt Democrat',NULL);
INSERT INTO race_seats VALUES ('OH',2,'David Taylor','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OH',3,'Joyce Beatty','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('OH',4,'Jim Jordan','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OH',5,'Bob Latta','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OH',6,'Michael Rulli','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OH',7,'Max Miller','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('OH',8,'Warren Davidson','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OH',9,'Marcy Kaptur','D','Lean/Tilt Democrat',NULL);
INSERT INTO race_seats VALUES ('OH',10,'Mike Turner','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OH',11,'Shontel Brown','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('OH',12,'Troy Balderson','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OH',13,'Emilia Sykes','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('OH',14,'David Joyce','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AZ',1,'Schweikert','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('AZ',2,'Eli Crane','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AZ',3,'Yassamin Ansari','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('AZ',4,'Greg Stanton','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('AZ',5,'Biggs','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AZ',6,'Juan Ciscomani','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('AZ',7,'Raul Grijalva','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('AZ',8,'Abraham Hamadeh','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AZ',9,'Paul Gosar','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MI',1,'Jack Bergman','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MI',2,'John Moolenaar','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MI',3,'Hillary Scholten','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MI',4,'Bill Huizenga','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('MI',5,'Tim Walberg','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MI',6,'Debbie Dingell','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MI',7,'Tom Barrett','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('MI',8,'Kristen Rivet','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MI',9,'Lisa McClain','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MI',10,'James','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('NC',1,'Don Davis','D','Tossup',NULL);
INSERT INTO race_seats VALUES ('NC',2,'Deborah Ross','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NC',3,'Greg Murphy','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NC',4,'Valerie Foushee','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NC',5,'Virginia Foxx','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NC',6,'Addison McDowell','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NC',7,'David Rouzer','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NC',8,'Mark Harris','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NC',9,'Richard Hudson','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NC',10,'Pat Harrigan','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NC',11,'Chuck Edwards','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('NC',12,'Alma Adams','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NC',13,'Tim Moore','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NV',1,'Dina Titus','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NV',2,'Amodei','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NV',3,'Susie Lee','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NV',4,'Steven Horsford','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('GA',1,'Carter','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('GA',2,'Sanford Bishop','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('GA',3,'Brian Jack','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('GA',4,'Hank Johnson','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('GA',5,'Nikema Williams','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('GA',6,'Lucy McBath','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('GA',7,'Rich McCormick','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('GA',8,'Austin Scott','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('GA',9,'Andrew Clyde','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('GA',10,'Collins','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('GA',11,'Loudermilk','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('GA',12,'Rick Allen','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('GA',13,'Scott','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('GA',14,'Greene','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('IL',1,'Jonathan Jackson','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',2,'Kelly','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',3,'Delia Ramirez','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',4,'García','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',5,'Mike Quigley','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',6,'Sean Casten','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',7,'Davis','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',8,'Raj Krishn.','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',9,'Schakowsky','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',10,'Brad Schneider','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',11,'Bill Foster','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',12,'Mike Bost','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('IL',13,'Nikki Budzinski','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',14,'Lauren Underwood','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('IL',15,'Mary Miller','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('IL',16,'Darin LaHood','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('IL',17,'Eric Sorensen','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WA',1,'Suzan DelBene','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WA',2,'Rick Larsen','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WA',3,'Marie Perez','D','Tossup',NULL);
INSERT INTO race_seats VALUES ('WA',4,'Newhouse','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('WA',5,'Michael Baumgartner','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('WA',6,'Emily Randall','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WA',7,'Pramila Jayapal','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WA',8,'Kim Schrier','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WA',9,'Adam Smith','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WA',10,'Marilyn Strickland','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WI',1,'Bryan Steil','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('WI',2,'Mark Pocan','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WI',3,'Derrick Van Orden','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('WI',4,'Gwenn Moore','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('WI',5,'Scott Fitzgerald','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('WI',6,'Glenn Grothman','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('WI',7,'Tiffany','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('WI',8,'Tony Wied','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MN',1,'Brad Finstad','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MN',2,'Craig','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MN',3,'Kelly Morrison','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MN',4,'Betty McCollum','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MN',5,'Ilhan Omar','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MN',6,'Tom Emmer','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MN',7,'Mischelle Fischbach','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MN',8,'Pete Stauber','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NH',1,'Pappas','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NH',2,'Maggie Goodlander','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NJ',1,'Donald Norcross','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NJ',2,'Jeff Van Drew','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NJ',3,'Herb Conaway','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NJ',4,'Chris Smith','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NJ',5,'Josh Gottheimer','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NJ',6,'Frank Pallone','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NJ',7,'Thomas Kean','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('NJ',8,'Rob Menendez','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NJ',9,'Nellie Pou','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NJ',10,'LaMonica McIver','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NJ',11,'Sherrill','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NJ',12,'Coleman','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('RI',1,'Gabe Amo','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('RI',2,'Seth Magaziner','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MD',1,'Andrew P. Harris','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MD',2,'Johnny Olszewski','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MD',3,'Sarah Elfreth','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MD',4,'Glenn Ivey','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MD',5,'Hoyer','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MD',6,'April McClain-Delaney','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MD',7,'Kweisi Mfume','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MD',8,'Jamie Raskin','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('DE',0,'Sarah McBride','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CT',1,'John Larson','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CT',2,'Joe Courtney','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CT',3,'Rosa DeLauro','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CT',4,'Jim Himes','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('CT',5,'Jahana Hayes','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('KS',1,'Tracey Mann','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('KS',2,'Derek Schmidt','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('KS',3,'Sharice Davids','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('NE',1,'Mike Flood','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('NE',3,'Adrian Smith','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('IA',1,'Mariannette Miller-Meeks','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('IA',2,'Hinson','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('IA',3,'Zach Nunn','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('KY',1,'James Comer','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('KY',2,'Brett Guthrie','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('KY',3,'Morgan McGarvey','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('KY',4,'Thomas Massie','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('KY',5,'Hal Rogers','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OK',1,'Hern','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OK',2,'Josh Brecheen','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OK',3,'Frank Lucas','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OK',4,'Tom Cole','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('OK',5,'Stephanie Bice','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('WV',1,'Carol Miller','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('WV',2,'Riley Moore','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('ND',0,'Julie Fedorchak','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AK',0,'Nick Begich','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('UT',1,'Moore','R','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('UT',2,'Celeste Maloy','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('UT',3,'Mike Kennedy','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('UT',4,'Burgess Owens','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('VT',0,'Becca Balint','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('HI',1,'Ed Case','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('HI',2,'Jill Tokuda','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('ME',1,'Chellie Pingree','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('ME',2,'Golden','D','Likely Republican',NULL);
INSERT INTO race_seats VALUES ('AR',1,'Rick Crawford','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AR',2,'French Hill','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AR',3,'Steve Womack','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('AR',4,'Bruce Westerman','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('LA',1,'Steve Scalise','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('LA',2,'Troy Carter','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('LA',3,'Clay Higgins','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('LA',4,'Mike Johnson','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('LA',5,'Letlow','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('LA',6,'Cleo Fields','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MS',1,'Trent Kelly','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MS',2,'Bennie Thompson','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('MS',3,'Michael Guest','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('MS',4,'Mike Ezell','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('SC',1,'Mace','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('SC',2,'Joe Wilson','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('SC',3,'Sheri Biggs','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('SC',4,'William Timmons','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('SC',5,'Norman','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('SC',6,'Jim Clyburn','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('SC',7,'Russell Fry','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TN',1,'Diana Harshbarger','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TN',2,'Tim Burchett','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TN',3,'Chuck Fleischmann','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TN',4,'Scott DesJarlais','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TN',5,'Andy Ogles','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TN',6,NULL,'R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TN',7,'Mark Green','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TN',8,'David Kustoff','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('TN',9,'Cohen','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('VA',1,'Rob Wittman','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('VA',2,'Jennifer Kiggans','R','Tossup',NULL);
INSERT INTO race_seats VALUES ('VA',3,'Bobby Scott','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('VA',4,'Jennifer McClellan','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('VA',5,'Eugene Vindman','D','Safe Democrat',NULL);
INSERT INTO race_seats VALUES ('VA',6,'Ben Cline','R','Safe Republican',NULL);
INSERT INTO race_seats VALUES ('VA',7,'Abigail Spanberger','D','Safe Democrat',NULL);
